//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FinkiEscapa.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("FinkiEscapa.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap classroom {
            get {
                object obj = ResourceManager.GetObject("classroom", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Успешно ги завршивте сите игри. 
        ///Кодот за излез е: {0}.
        /// </summary>
        internal static string codeMessage {
            get {
                return ResourceManager.GetString("codeMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap endBoxBg {
            get {
                object obj = ResourceManager.GetObject("endBoxBg", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ExitDoor {
            get {
                object obj = ResourceManager.GetObject("ExitDoor", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Дали сте сигурни дека сакате да излезите од играта?.
        /// </summary>
        internal static string exitMessage {
            get {
                return ResourceManager.GetString("exitMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Излези?.
        /// </summary>
        internal static string exitMessageTitle {
            get {
                return ResourceManager.GetString("exitMessageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ја завршивте &quot;{0}&quot; играта.
        /// </summary>
        internal static string finishedGameMessage {
            get {
                return ResourceManager.GetString("finishedGameMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to game1.
        /// </summary>
        internal static string game1Name {
            get {
                return ResourceManager.GetString("game1Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to game2.
        /// </summary>
        internal static string game2Name {
            get {
                return ResourceManager.GetString("game2Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Меморија.
        /// </summary>
        internal static string game3Name {
            get {
                return ResourceManager.GetString("game3Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IQ Квиз.
        /// </summary>
        internal static string game4Name {
            get {
                return ResourceManager.GetString("game4Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to game5.
        /// </summary>
        internal static string game5Name {
            get {
                return ResourceManager.GetString("game5Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to game6.
        /// </summary>
        internal static string game6Name {
            get {
                return ResourceManager.GetString("game6Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap icon_null {
            get {
                object obj = ResourceManager.GetObject("icon-null", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap IQQuizIcon {
            get {
                object obj = ResourceManager.GetObject("IQQuizIcon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap keypad {
            get {
                object obj = ResourceManager.GetObject("keypad", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap mainMenuBg {
            get {
                object obj = ResourceManager.GetObject("mainMenuBg", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap memotyIcon {
            get {
                object obj = ResourceManager.GetObject("memotyIcon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap menuBg2 {
            get {
                object obj = ResourceManager.GetObject("menuBg2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Треба прво да ја завршите &quot;{0}&quot; играта за да можете да го ја отворите оваа игра .
        /// </summary>
        internal static string notFinishedGameMessage {
            get {
                return ResourceManager.GetString("notFinishedGameMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap pcDialog {
            get {
                object obj = ResourceManager.GetObject("pcDialog", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap pcMonitor {
            get {
                object obj = ResourceManager.GetObject("pcMonitor", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap powerOff {
            get {
                object obj = ResourceManager.GetObject("powerOff", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap powerOn {
            get {
                object obj = ResourceManager.GetObject("powerOn", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap wireConnect {
            get {
                object obj = ResourceManager.GetObject("wireConnect", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
